---
- hosts: semaphore-servers
  user: vagrant
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: pkg_name
      prompt: Which package to install?
  tasks:
  - name: Install selected package
    action: apt name={{ pkg_name }} state=installed
