---
- hosts: semaphore-servers
  vars_prompt:
    - name: pkg_name
      prompt: Which package to install?
  tasks:
  - name: Install selected package
    action: apt name={{ pkg_name }} state=installed
